### ISSUE TITLE
Unauthorized error & Unable to find repository name

### ISSUE THREAD

**Issue by ShaunLWM** [elgohr/Github-Hub-Action#4]
I was playing around with your action on a private repository account on which I got 2 separate error.

The first was 401 Unauthorized. This snippet was mixed with other actions.
```
    - name: Create Sample Release
      uses: elgohr/Github-Release-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: MyReleaseMessage
```

![401](https://i.imgur.com/eWnTEUE.png)

I tried it the second time but purely with the YAML syntax you've provided.
```
name: Publish Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create a Release
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release create $(date +%Y%m%d%H%M%S)
```
![Error](https://i.imgur.com/qtqGjPL.png)

I'm lost looking at the second error especially.
Any help would be appreciated. Thank you!

Edit: my lord.. I realized I'm mixing up the repository name. Will do a check and get back to you once again.

Edit2: okay the README has the wrong info.  Sent a pull request.

Edit3:
```
name: Publish Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create a Release
      uses: elgohr/Github-Hub-Action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release create $(date +%Y%m%d%H%M%S)
```

Error
```
Error creating release: Unauthorized (HTTP 401)
Bad credentials
```

**Comment by elgohr** [comment]
Hey,
I would like to point out that Github-Release-Action, Publish-Docker-Github-Action and Github-Hub-Action are totally different actions. Are you probably mixing up things?
Would be great, if you could clean up the issue. At the moment the edits are more confusing than helping...

**Comment by ShaunLWM** [comment]
Okay I apologize. I was so confused from all the similar actions (and probably my tabs as well). I sit down and take a good look into trying out this action again. Will report to you if there's any problem again.

Once again, sorry for all the confusion. And thank you so much for your help.

**Comment by OmgImAlexis** [comment]
I'm getting the same issue. How did you resolve this?

```
Error creating release: Unauthorized (HTTP 401)
Bad credentials
```

```yaml
- name: Create a Release
  uses: elgohr/Github-Hub-Action@master
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    args: release create $(date +%Y%m%d%H%M%S)
```
